var express = require('express')
var multer = require('multer')
var AWS = require('aws-sdk')
var fs = require('fs')
var path = require('path')
const swaggerJsDoc = require('swagger-jsdoc');
const swaggerUI = require('swagger-ui-express');

require("dotenv").config();
const port = process.env.port || 3000;

var app = express()

const options = {
    swaggerDefinition: {
        info: {
            title: 'AWS Recognition PPE Detection API',
            version: '1.0.0',
            description: 'AWS Recognition PPE Detection API autogenerated by swagger'
        },
        host:'localhost:3000',
        basePath:'/'
    },
    apis:['app.js']
};

const specs = swaggerJsDoc(options);

app.use('/docs', swaggerUI.serve, swaggerUI.setup(specs));

var localFileName = "";
var storage = multer.diskStorage({
    destination: function (req, file, cb) {
        cb(null, __dirname + '/images/')
    },
    filename: function (req, file, cb) {
        localFileName = Date.now() + "-" + file.originalname
        cb(null, localFileName)
    }
});

var upload = multer({ 
    storage: storage,
    fileFilter: function (req, file, callback) {
        var ext = path.extname(file.originalname);
        if(ext !== '.png' && ext !== '.jpg' && ext !== '.jpeg') {
            return callback(new Error('Only images are allowed'))
        }
        callback(null, true)
    }
})

AWS.config.update({
    accessKeyId: process.env.AWS_ACCESS_KEY_ID,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
    region: process.env.AWS_REGION
})

function getFile(path) {
    try {
        const image = fs.readFileSync(path)
        return (image)
    }
    catch (e) {
        console.error(e.message)
        process.exit()
    }
}
const rekognition = new AWS.Rekognition();


/**
 * @swagger
 * /profile:
 *   post:
 *     description: Return the PPE detection of an image uploaded
 *     consumes:
 *       - multipart/form-data
 *     parameters:
 *       - in: formData
 *         name: image
 *         type: file
 *         description: The file to upload.
 *     produces:
 *       - application/json
 *     responses:
 *       200:
 *         description: Response from AWS rekognition with details of PPE detection
 *       400:
 *         description: File can't be empty
 *       500:
 *         description: Only images are allowed
 */
app.post('/profile', upload.any(), function (req, res) {
    if(localFileName.length == 0)
        res.status(400).send("File can't be empty");
    var params = {
        Image: {
            Bytes: getFile(`./images/${localFileName}`)
        }
    };
    
    rekognition.detectProtectiveEquipment(params, function (err, data) {
        if (err) console.log("err: ", err, err.stack);
        else {
            console.log("data: ", data);
            res.json(data);
        }
    });
});
app.listen(port, () => {
    console.log(`Example app listening at http://localhost:${port}`);
});